### ISSUE TITLE
Whitelist is ignored

### ISSUE THREAD

**Issue by ProsperCraft** [runescapejon/Minecraft-Backpack-Mod#1]
as of backpack-2.2.1-1.7.x the whitelist that is set up with shift+backpack key is now ignored it picks up most things on the ground now.

**Comment by runescapejon** [comment]
can you please give me more informaion

**Comment by ProsperCraft** [comment]
Pre-update behavior- shift+b opens the interface where you place your backpack on your back, and put in objects that are auto collected by the backpack.

Post-update behavior -shift+b opens the interface where you place your backpack on your back, and you can put objects to be auto collected, but it is ignored and it picks up whatever it wants.
Also if you are standing on something that doesn't fit in your inventory, you are unable to open your backpack, it keeps closing itself, I think it is directly related to the problem after the update.

**Comment by runescapejon** [comment]
while having the old version of the backpack in the server did you update it with the new backpack mod?
like replace it

**Comment by Dream-Master** [comment]
We replace it using now your version 2.2.1 instead of 2.0.1.

**Comment by runescapejon** [comment]
https://github.com/runescapejon/Minecraft-Backpack-Mod/releases/tag/2.2.2

**Comment by runescapejon** [comment]
I have tested this and it works well but as for the blocks that are selected in the gui and auto pickup i think i fixed reason why i said i think because i cannot reproduce the error since you guys didn't deleted the Backpack data files and start new let me know if there any problems

**Comment by Dream-Master** [comment]
I will update today and then we will test it.

**Comment by Dream-Master** [comment]
Work with newest Version.

**Comment by ProsperCraft** [comment]
Fixed now, thank you, you are awesome!
