### ISSUE TITLE
Please block backpacks from opening in the spirit dim

### ISSUE THREAD

**Issue by ProsperCraft** [runescapejon/Minecraft-Backpack-Mod#2]
backpacks bypass the block on bringing things from the overworld into the spirit dim, please block opening of them in the spirit world.

**Comment by runescapejon** [comment]
What the Spirit World ?

**Comment by Dream-Master** [comment]
I can do that with the mod BlockLimiter for the GT New Horizons Pack.
@Goshen
did you know wich dim ?
@runescapejon 
I think this is a Dimension from Witchery where you go empty in. In my Pack i can fix it with Block Limiter maybe but for other Packs it would be nice to write a compatiblity patch.

**Comment by runescapejon** [comment]
This might be Witchery issue but I 'll see if i can do anything

**Comment by runescapejon** [comment]
This is an issue with Witchery mod that kinda of mod haven't been updated in while so I'm sure there alot of issue with the mod

**Comment by ProsperCraft** [comment]
@Dream-Master you can keep the pack from opening when someone presses the backpack key?

**Comment by Dream-Master** [comment]
@ProsperCraft 
Not sure if Block Limiter handle it ? I think it handle only Block placing and item right clicking.

**Comment by ProsperCraft** [comment]
which is why we need the backpack mods(both of them) to check if they are in the spirit dim and not open if they are.

**Comment by Dream-Master** [comment]
Ok Adventure BAckpack you can take on the shoulder with you but the normal backpack you have in your inventory and not take with you.

**Comment by ProsperCraft** [comment]
no, normal backpacks can be put on your back as well.  you hold shift and
press the backpack key and you can put it on your back.

**Comment by Dream-Master** [comment]
Ok i found a Backpack open Key but this dont working.

**Comment by ProsperCraft** [comment]
yea, you need to remap it for it to work, it has a conflict, I set mine to ;

**Comment by Dream-Master** [comment]
Ok works now. You can take items with you to the dream dim. Ok need to be fixed too.

**Comment by runescapejon** [comment]
wont fix because this is Witchery issue
