### ISSUE TITLE
Disallowed Items

### ISSUE THREAD

**Issue by Sarrumkun** [runescapejon/Minecraft-Backpack-Mod#3]
Disallowed Items within the config does not seem to be working. I copy and pasted the example(1,5:2,ingotSilver) then reloaded minecraft and crafted a new backpack but stone, birch wood planks, and every type of silver ingot from the example is still being allowed in the backpack. I also used a dozen or so other items with the same result.

Please and Thank You,
Sarrum

**Comment by runescapejon** [comment]
Can you show me your config please

**Comment by Sarrumkun** [comment]
the backpack config?I dropboxed it for you https://www.dropbox.com/s/faic2zshw77wvu8/Backpack.cfg?dl=0

**Comment by Sarrumkun** [comment]
if you mean the full config folder for everything in the pack https://www.dropbox.com/s/7ga2yglc4wphnmb/config.zip?dl=0

**Comment by runescapejon** [comment]
ahh i see the problem the code don't support item ID for the config option to work you would have to type out the block for an example to disallow stone you would have to do this 
`S:disallowItems=stone`

**Comment by Sarrumkun** [comment]
oh okay, and for other items such as silver ingots or mod items? Could you give me a few examples so I know I am doing it correctly?

**Comment by runescapejon** [comment]
Going to improve the disallow feature

**Comment by Sarrumkun** [comment]
okay cool! Thank you very much for looking into this for me. I await your improvements to the feature then :dancer: !

**Comment by Sarrumkun** [comment]
o/ It has been about a month and was just wondering how the enhancement is going. Hope things are going well! Have an awesome day :)

**Comment by runescapejon** [comment]
ah sorry, I didn't mange to make any improvement because at the time i was super busy because my computer had broke then i had a lot of other work to do that was important

**Comment by Sarrumkun** [comment]
np :) just figured id check in

**Comment by runescapejon** [comment]
@Sarrumkun https://github.com/runescapejon/Minecraft-Backpack-Mod/releases
